# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example
# cool

name = "Hugo Fabric Fork"
license = "MIT"
licenselink = "https://github.com/wd/hugo-fabric/blob/master/LICENSE"
description = "hugo-fabric-fork"
homepage = "https://github.com/wd/hugo-fabric"
tags = ["blog", "archives", "tags"]
features = ["blog"]
min_version = 0.19+

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = "Hugo Fabric"
  homepage = "https://github.com/wd/hugo-fabric"
  repo = "https://github.com/wd/hugo-fabric"
